name: Auto Redeploy

on:
  schedule:
    # 分 時 日 月 曜 日本時間から-9でUTC時間
    - cron: '15 3 * * *'
    - cron: '15 7 * * *'
    - cron: '15 11 * * *'
    - cron: '15 15 * * *'
    - cron: '15 19 * * *'
    - cron: '50 21 * * *'
    - cron: '35 23 * * *'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy